# Generated by Django 5.1 on 2024-09-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='adresse',
            field=models.CharField(max_length=280, null=True),
        ),
    ]
