FROM python:latest

# mon répertoire de travail
WORKDIR /monappli

# Copie des fichiers nécessaires
COPY requirement.txt .
RUN pip install -r requirement.txt

# Copier du projet
COPY . .
#lancement serveur
CMD ["python", "myproject/manage.py", "runserver", "0.0.0.0:8000"]
