FROM python:latest

# Définir le répertoire de travail
WORKDIR /monappli

# Copier les fichiers nécessaires
COPY requirement.txt .
RUN pip install -r requirement.txt

# Copier le reste du projet
COPY . .

# Exposer le port 8000 pour le frontend
EXPOSE 8000

# Commande pour lancer le serveur Django
CMD ["python", "myproject/manage.py", "runserver", "0.0.0.0:8000"]
